#!/bin/bash 

COST_PINEAPPLE=50
a=$((COST_PINEAPPLE * 1))
COST_BANANA=4
b=$((COST_BANANA * 2))
COST_WATERMELON=23
c=$((COST_WATERMELON * 3))
COST_BASKET=1

TOTAL=$((a + b + c + $COST_BASKET))

echo "Total Cost is $TOTAL"